### ISSUE TITLE
[BUG] Yeta Wrench doesnt break conduits fully

### ISSUE THREAD

**Issue by Neylux** [agnor99/EnderIO-Rewrite#1]
**The bug**
Yeta Wrench does give u the conduit when shift-clicking on the conduit but it leaves behind an invisible block which prevents any other block from being placed there ever again.

**To Reproduce**
1. Go to any placed conduit
2. Sneak-click on placed conduit to break with Yeta-Wrench
3. After the break try to place another block onto the same spot
4. Unable to place any new block or conduit onto the broken spot

**Expected behavior**
Yeta Wrench should not leave behind weird invisible block instead it should work just like breaking the conduit by hand.

**Screenshots**
-

**Version information:**
 - OS: [Windows]
 - Java version  [not important]
 - Minecraft version [1.19.2]
 - EnderCore version [-]
 - Version [EnderIO-6.0.20-alpha-nightly-all] (Conduit version)

**Additional context**
Not really sure if this behaviour is only because of this slimmed version of EnderIO

**Comment by Unbistrackted** [comment]
https://cdn.discordapp.com/attachments/1007089844624838780/1031724710104416306/unknown_2022.10.17-20.40_1.mp4

A short video showing the bug

**Comment by agnor99** [comment]
thanks, will take a look at it asap
