### ISSUE TITLE
not really a crash but stacking an item and any other conduit will bug the texture

### ISSUE THREAD

**Issue by taraxsmallboy** [agnor99/EnderIO-Rewrite#2]
**The bug**
stacking an item and any other conduit next to each other will bug the texture

**To Reproduce**
Place 2 item conduits and energy conduits next to each other
**The Version**
minecraft 1.19.2 forge 43.1.43
![weird_render_bug](https://user-images.githubusercontent.com/93595333/196175369-743b90ee-5259-439c-834e-c257c79f4a97.png)

**Comment by agnor99** [comment]
it's not a bug. It's intential as the connections that contain multiple conduits can't be in the same place in different blocks without the central box of the conduit looking weird sometimes
reference to older enderio version to show the same box with a non purple surrounding color
![image](https://user-images.githubusercontent.com/36055315/196478770-ef2aa5ba-19c8-40f1-9dc9-3e699f3c7f9e.png)
