### ISSUE TITLE
[BUG] Map won't load/World corruption

### ISSUE THREAD

**Issue by Unbistrackted** [agnor99/EnderIO-Rewrite#3]
**The bug**
Error loading the map/Map corruption

**To Reproduce**
1. Create a world
2. Place any conduit
3. Save & re-enter the map

**Expected behavior**
The map should load.

**Screenshots**
https://pastebin.com/9Cgv4p7E

![image](https://user-images.githubusercontent.com/112902220/196307794-3e566c39-1cde-4bd4-b1ca-6638195972ac.png)
![image](https://user-images.githubusercontent.com/112902220/196307829-8b358cf3-8c9d-42cf-a9cd-60f903fc1e33.png)

**Version information:**
 - OS: Windows
 - Java version: 
 - Minecraft version:  1.19.2
 - EnderCore version [e.g. 1.0.0]
 - Version [e.g. 6.0.0]

**Comment by agnor99** [comment]
fixed in newest version
