### ISSUE TITLE
[BUG] Terminal Orientation

### ISSUE THREAD

**Issue by Unbistrackted** [agnor99/EnderIO-Rewrite#4]
**The bug**
AE2 Terminal doesn't connect properly with enderIO cables & wrong orientation

**To Reproduce**
1. Place AE2 Terminal
2. Try to connect it with the ME enderIo cable

**Expected behavior**
AE2 terminal should have been oriented and connected properly with EIO ME conduit.

**Screenshots**

![image](https://user-images.githubusercontent.com/112902220/196308396-89e59889-80d9-4980-8910-a59f8cdaf3f6.png)

**Version information:**

 - OS: [Windows]
 - Java version [17]
 - Minecraft version [1.19.2]
 - EnderCore version [e.g. 1.0.0]
 - Version [EnderIO-6.0.20-alpha-nightly-all] - 'Conduits version'

**Comment by agnor99** [comment]
thanks for the report, the terminal orientation isn't wrong, they can only face outwards. the conduit trying to connect to the terminal is wrong, fixed in 6.0.21
