### ISSUE TITLE
[BUG] AE2 Terminal doesn't connect to ME Conduit

### ISSUE THREAD

**Issue by Unbistrackted** [agnor99/EnderIO-Rewrite#5]
**The bug**
I can't place the conduit "on the same block" as the terminal (Which should) to connect to it.

**To Reproduce**
1. Place any AE2 terminal (or the Interface with the same shape)
2. Try to connect it with ME conduit

**Expected behavior**
It should connect properly connect to the terminal and "re-orient" itself

**Screenshots**
![image](https://user-images.githubusercontent.com/112902220/196506267-1d426e31-fb15-4c48-b059-bc129ab0677e.png)

**IMPORTANT & Addition to that**
Things like export/import bus, P2P, or any AE2 block that needs the cable within the same block will not connect

**Version information:**
 - OS: [Windows]
 - Java version [17]
 - Minecraft version [1.19.2]
 - Version [6.0.22 (Conduit only)]

(I forgot to say about needing to be on the same block as the terminal in the last bug report)

**Comment by agnor99** [comment]
conduits can't be placed into the same block as ae2 multipart blocks, conduits just relay channels
