### ISSUE TITLE
[BUG] ME conduit "not physically" connecting to the cable

### ISSUE THREAD

**Issue by Unbistrackted** [agnor99/EnderIO-Rewrite#6]
**The bug**
ME conduit connects to AE2 cables, but its "model" doesn't
(For some reason, when I try to connect any AE2 cable to another side of the conduit, it appears the "flat" thing that connects on the "face" that was first connected....)

**To Reproduce**
1. Place AE2 cable
2. Connect it with ME conduit

**Expected behavior**
It should connect "properly"/"physically" with the cable 

**Screenshots**

![image](https://user-images.githubusercontent.com/112902220/196508573-913a3a8b-02a7-4716-923c-30b4d8a79ec3.png)
![image](https://user-images.githubusercontent.com/112902220/196508607-b53edfef-f49b-4eee-83c1-e1de19748f03.png)
![image](https://user-images.githubusercontent.com/112902220/196508646-900031f2-3e4b-4df5-b250-06b512ac6cd3.png)

**Version information:**
 - OS: [Windows]
 - Java version [17]
 - Minecraft version [1.19.2]
 - Version [6.0.22]
 
 **Additional info**
 When I was testing, looks like it only appears when something is connected to that cable (Both the conduit and the AE2 Cable)

**Comment by agnor99** [comment]
fixed by allowing conduit types to say if they want to update their connection a tick later
