### ISSUE TITLE
[BUG] ME dense conduit doesn't have 32 channels

### ISSUE THREAD

**Issue by Unbistrackted** [agnor99/EnderIO-Rewrite#7]
**The bug**
ME dense conduit doesn't have 32 channels

**To Reproduce**
1. Place 9 interfaces (or any block that takes a channel on the AE2 System)
2. Connect them all with conduits
2. The 9th block will not be connected

**Expected behavior**
Dense conduit should have more than 8 channels

**Screenshots**
![image](https://user-images.githubusercontent.com/112902220/196512518-9caf0b13-96a3-462d-bef1-ec42ed1b7f5c.png)
![image](https://user-images.githubusercontent.com/112902220/196512549-d8a123a5-0e6c-4172-91b6-ad7c64410d6e.png)
![image](https://user-images.githubusercontent.com/112902220/196512350-284eb80b-50d6-4b03-aa5e-491ca19dd596.png)

**Version information:**
 - OS: [Windows]
 - Java version [17]
 - Minecraft version [1.19.2]
 - Version [6.0.22]

**Comment by agnor99** [comment]
![image](https://user-images.githubusercontent.com/36055315/196524415-482cd7aa-d941-4d97-8823-1b828b852265.png)
Dense ME-Conduit has 32 channels, interfaces can only relay 7 of them(they keep on for themself and you can connect up to 7 more)
